// <auto-generated />
namespace Colander.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nullableColanderID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullableColanderID));
        
        string IMigrationMetadata.Id
        {
            get { return "201606170624395_nullableColanderID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
